#!/bin/bash

export APP_NAME=<%= name %>

if [ "$APP_NAME" = "" ]; then
  echo "APP_NAME must be set."
  exit;
fi

if [ "$1" = "prd" ]; then
  echo "Pushing configuration to production"
  s=""
  while IFS='' read -r line || [[ -n "$line" ]]; do
    s="$line $s"
  done < ".env.production"
  DOKKU_HOST=dokku.prd.paas.impero.me $HOME/.dokku/contrib/dokku_client.sh config:set $APP_NAME $s
else
  echo "Pushing configuration to staging"
  s=""
  while IFS='' read -r line || [[ -n "$line" ]]; do
    s="$line $s"
  done < ".env.staging"
  DOKKU_HOST=stg.paas.impero.me $HOME/.dokku/contrib/dokku_client.sh config:set $APP_NAME $s
fi
