'use strict'

const yeoman = require('yeoman-generator')
const chalk = require('chalk')
const emoji = require('node-emoji')
const yosay = require('yosay')
const extend = require('lodash').merge
const commandExists = require('command-exists')
const sortNpmDeps = require('./sortNpmDeps')

module.exports = yeoman.Base.extend({
  prompting () {
    // Have Yeoman greet the user.
    this.log(yosay(
      `Welcome to the ${chalk.yellow('Impero')} generator!`
    ))

    this.log(`\n---\nNote that Yeoman will generate the project within the CWD... ${emoji.get('skull_and_crossbones')}\n---\n`)

    const prompts = [{
      type: 'input',
      name: 'name',
      message: `Your project name (must be ${chalk.underline('unique')} and ${chalk.underline('alphanumeric only')})?`,
      //Defaults to the project's folder name if the input is skipped
      default: this.appname
    }, {
      type: 'input',
      name: 'description',
      message: 'Your project description?',
      default: 'A new project generated by the Impero generator'
    }, {
      type: 'list',
      name: 'cssLang',
      message: 'Which CSS preprocessor?',
      // Sourdough is disabled until a Webpack-compatible loader is developed
      choices: [/*{
        name: 'Sourdough / SSS'
      }, */{
        name: 'Sass'
      }, {
        name: 'Sass (SCSS)'
      }, {
        name: 'Stylus'
      }],
      default: 0
    }, {
      type: 'list',
      name: 'jsLang',
      message: 'Which JS feature set? (all include ES2015 / Babel)',
      // TypeScript is disabled until the loader's compatibility with Node 6.x is fixed
      // Further development will likely be required after that point
      choices: [{
        name: 'Vanilla'
      }, {
        name: 'React'
      }/*, {
        name: 'TypeScript'
      }*/],
      default: 0
    }, {
      type: 'list',
      name: 'browserSupport',
      message: 'Browser support?',
      choices: [{
        name: 'Legacy (IE9+)',
      }, {
        name: 'Modern (Chrome, Firefox, Edge, Safari)'
      }],
      default: 0
    }, {
      type: 'confirm',
      name: 'copyEnv',
      message: 'Copy .env.example to .env?',
      default: true
    }, {
      type: 'confirm',
      name: 'installDeps',
      message: 'Install dependencies?',
      default: true
    }]

    return this.prompt(prompts).then(answers => {
      // To access props later use this.props.exampleAnswer
      this.props = answers

      // Pass the project name to a potential parent generator
      this.options.projectName = this.props.name

      if (this.props.browserSupport === 'Legacy (IE9+)') this.props.browserSupport = 'legacy'
      else if (this.props.browserSupport === 'Modern (Chrome, Firefox, Edge, Safari)') this.props.browserSupport = 'modern'

      // Make object of CSS choice details
      this.props.cssLang = {
        name: this.props.cssLang
      }

      // Add additional details for each option
      // Better than making a load of additional files to copy instead
      switch (this.props.cssLang.name) {
        case 'Sourdough / SSS':
          this.props.cssLang.templateDir = 'sourdough'
          this.props.cssLang.loader = 'TODO'
          this.props.cssLang.fileExt = 'sss'
          break
        case 'Sass':
          this.props.cssLang.templateDir = 'sass'
          this.props.cssLang.loader = 'sass'
          this.props.cssLang.fileExt = 'sass'
          break
        case 'Sass (SCSS)':
          this.props.cssLang.templateDir = 'scss'
          this.props.cssLang.loader = 'sass'
          this.props.cssLang.fileExt = 'scss'
          break
        case 'Stylus':
          this.props.cssLang.templateDir = 'stylus'
          this.props.cssLang.loader = 'stylus'
          this.props.cssLang.fileExt = 'styl'
          break
        // This should never happen
        default:
          break
      }

      // And do the same for JS
      this.props.jsLang = {
        name: this.props.jsLang
      }

      switch (this.props.jsLang.name) {
        case 'Vanilla':
          this.props.jsLang.templateDir = 'vanilla'
          this.props.jsLang.loader = 'babel'
          this.props.jsLang.fileExt = 'js',
          this.props.jsLang.linter = 'eslint'
          break
        case 'React':
          this.props.jsLang.templateDir = 'react'
          this.props.jsLang.loader = 'babel'
          this.props.jsLang.fileExt = 'js',
          this.props.jsLang.linter = 'eslint'
          break
        case 'TypeScript':
          this.props.jsLang.templateDir = 'typescript'
          this.props.jsLang.loader = 'babel!ts?sourceMap'
          this.props.jsLang.fileExt = 'ts',
          this.props.jsLang.linter = 'tslint'
          break
        // This should never happen
        default:
          break
      }
    })
  },

  writing () {
    // Copy templated files
    this.fs.copyTpl(
      this.templatePath('.editorconfig'),
      this.destinationPath('.editorconfig'), {
        cssExt: this.props.cssLang.fileExt
      }
    )
    this.fs.copyTpl(
      this.templatePath('package.json'),
      this.destinationPath('package.json'), {
        name: this.props.name,
        description: this.props.description,
        cssLang: this.props.cssLang.name,
        cssLoader: this.props.cssLang.loader
      }
    )
    this.fs.copyTpl(
      this.templatePath('_README.md'),
      this.destinationPath('README.md'), {
        name: this.props.name,
        cssName: this.props.cssLang.name,
        jsName: this.props.jsLang.name,
        browserSupport: this.props.browserSupport
      }
    )
    this.fs.copyTpl(
      this.templatePath('webpack.config.js'),
      this.destinationPath('webpack.config.js'), {
        cssLang: this.props.cssLang.name,
        cssLoader: this.props.cssLang.loader,
        cssExt: this.props.cssLang.fileExt,
        jsLang: this.props.jsLang.name,
        jsLoader: this.props.jsLang.loader,
        jsExt: this.props.jsLang.fileExt,
        jsLinter: this.props.jsLang.linter,
        browserSupport: this.props.browserSupport
      }
    )
    this.fs.copyTpl(
      this.templatePath('webpack.production.config.js'),
      this.destinationPath('webpack.production.config.js'), {
        cssLang: this.props.cssLang.name,
        cssLoader: this.props.cssLang.loader,
        cssExt: this.props.cssLang.fileExt,
        jsLang: this.props.jsLang.name,
        jsLoader: this.props.jsLang.loader,
        jsExt: this.props.jsLang.fileExt,
        jsLinter: this.props.jsLang.linter,
        browserSupport: this.props.browserSupport
      }
    )

    // Copy untemplated files
    this.fs.copy(
      this.templatePath('.env.example'),
      this.destinationPath('.env.example')
    )
    if (this.props.copyEnv) this.fs.copy(
      this.templatePath('.env.example'),
      this.destinationPath('.env')
    )
    if (this.props.jsLang.name !== 'TypeScript') this.fs.copyTpl(
      this.templatePath('.eslintrc'),
      this.destinationPath('.eslintrc'), {
        jsLang: this.props.jsLang.name
      }
    )
    // Prefixed with an underscore, else npm will rename it to .npmignore
    this.fs.copy(
      this.templatePath('_.gitignore'),
      this.destinationPath('.gitignore')
    )
    if (this.props.jsLang.name === 'TypeScript') this.fs.copy(
      this.templatePath('tslint.json'),
      this.destinationPath('tslint.json')
    )
    this.fs.copy(
      this.templatePath('app/assets/humans.txt'),
      this.destinationPath('app/assets/humans.txt')
    )
    this.fs.copy(
      this.templatePath('app/assets/img'),
      this.destinationPath('app/assets/img')
    )
    this.fs.copy(
      this.templatePath('app/views'),
      this.destinationPath('app/views')
    )
    this.fs.copy(
      this.templatePath('app/index.js'),
      this.destinationPath('app/index.js')
    )
    this.fs.copy(
      this.templatePath('app/routes.js'),
      this.destinationPath('app/routes.js')
    )

    // Copy CSS
    this.fs.copy(
      this.templatePath(`app/src/_styles/${this.props.cssLang.templateDir}`),
      this.destinationPath('app/src/styles')
    )

    // Copy JS
    this.fs.copyTpl(
      this.templatePath(`app/src/_scripts/${this.props.jsLang.templateDir}/main.${this.props.jsLang.fileExt}`),
      this.destinationPath(`app/src/scripts/main.${this.props.jsLang.fileExt}`), {
        browserSupport: this.props.browserSupport
      }
    )
    this.fs.copy(
      this.templatePath(`app/src/_scripts/${this.props.jsLang.templateDir}/modules`),
      this.destinationPath('app/src/scripts/modules')
    )

    // Load dependencies from generated/copied package.json
    let deps = this.fs.readJSON(this.destinationPath('package.json'), {})

    // Define optional dependencies
    const legacyOptionalDeps = {
      'classlist.js': '^1.1.20150312',
      'es6-promise': '^4.0.3',
      'matchmedia-polyfill': '^0.3.0',
    }

    const cssOptionalDevDeps = {
      'Sass': {
        'breakpoint-sass': '^2.7.0',
        'node-sass': '^3.9.3',
        'sass-loader': '^4.0.2'
      },
      'Sass (SCSS)': {
        'breakpoint-sass': '^2.7.0',
        'node-sass': '^3.10.0',
        'sass-loader': '^4.0.2'
      },
      'Stylus': {
        'rupture': '^0.6.1',
        'stylus': '^0.54.5',
        'stylus-loader': '^2.3.1'
      }
    }

    const jsOptionalDeps = {
      'Vanilla': {},
      'React': {
        'react': '^15.3.2',
        'react-dom': '^15.3.2'
      },
      'TypeScript': {}
    }

    const jsOptionalDevDeps = {
      'Vanilla': {
        'babel-eslint': '^7.0.0',
        'eslint': '^3.5.0',
        'eslint-config-standard': '^6.0.1',
        'eslint-loader': '^1.5.0',
        'eslint-plugin-promise': '^2.0.1',
        'eslint-plugin-standard': '^2.0.0'
      },
      'React': {
        'babel-eslint': '^7.0.0',
        'babel-preset-react': '^6.11.1',
        'eslint': '^3.5.0',
        'eslint-config-standard': '^6.0.1',
        'eslint-config-standard-jsx': '^3.0.1',
        'eslint-config-standard-react': '^4.0.2',
        'eslint-loader': '^1.5.0',
        'eslint-plugin-promise': '^2.0.1',
        'eslint-plugin-react': '^6.3.0',
        'eslint-plugin-standard': '^2.0.0',
        'react-hot-loader': '^3.0.0-beta.5'
      },
      'TypeScript': {
        'ts-loader': '^0.8.2',
        'tslint': '^3.15.1',
        'tslint-loader': '^2.1.5',
        'typescript': '^1.8.10'
      }
    }

    // Merge them as selected
    if (this.props.browserSupport === 'legacy') extend(deps, {
      dependencies: legacyOptionalDeps
    })

    extend(deps, {
      dependencies: jsOptionalDeps[this.props.jsLang.name]
    })

    extend(deps, {
      devDependencies: cssOptionalDevDeps[this.props.cssLang.name]
    })

    extend(deps, {
      devDependencies: jsOptionalDevDeps[this.props.jsLang.name]
    })

    // Sort the dependencies
    sortNpmDeps(deps)

    // Write to file
    this.fs.writeJSON(this.destinationPath('package.json'), deps)
  },

  install () {
    if (!this.props.installDeps) return

    // Install dependencies in scaffolded package.json
    // Use Yarn if available
    commandExists('yarn', (err, yes) => {
      if (yes) {
        this.log(`\n---\nNearly done! All that's left now is to run ${chalk.bgYellow.black('yarn install')}. Here goes... ${emoji.get('v')}\n---\n`)
        this.spawnCommand('yarn', ['install'])
      } else {
        // The installDependencies function built-in to Yeoman does not work
        // inside this commandExists function:
        // this.installDependencies({ bower: false })
        this.log(`\n---\nNearly done! All that's left now is to run ${chalk.bgYellow.black('npm install')}. Here goes... ${emoji.get('v')}\n---\n`)
        this.spawnCommand('npm', ['install'])
      }
    })

    /* TODO install 'typings' globally if typescript
    if (this.props.jsLang.name === 'TypeScript') {
      //
    }
    */
  }
})
